Models/Insert.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum_Snackis.Models
{
    public class Insert
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public string Writer { get; set; }
        public string WriterNickName { get; set; }
        public string Subject { get; set; }
        public string Thread { get; set; }
        public string Text { get; set; }
        public bool Offensive { get; set; }
        public string PhotoLink { get; set; }
        public int Like { get; set; }
        public int Dislike { get; set; }
        public int Hearts { get; set; }
        public int ParentId { get; set; }
    }
}

Models/Thread.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum_Snackis.Models
{
    public class Thread
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public string WriterId { get; set; }
    }
}

Controllers/InsertsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Forum_Snackis.Data;
using Forum_Snackis.Models;
using Microsoft.EntityFrameworkCore;

namespace Forum_Snackis.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class InsertsController : ControllerBase
    {
        private readonly Forum_SnackisContext _context;

        public InsertsController(Forum_SnackisContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<ActionResult<List<Insert>>> GetInsertsController()
        {
            return await _context.Inserts.ToListAsync();
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<Insert>> GetInsert(int id)
        {
            var insert = await _context.Inserts.FindAsync(id);

            if (insert == null)
            {
                return NotFound();
            }

            return insert;
        }

        
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Forum_Snackis.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Forums.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Forum_Snackis.Data;
using Forum_Snackis.Models;
using Forum_Snackis.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;

namespace Forum_Snackis.Pages
{
    public class ForumsModel : PageModel
    {
        private readonly Forum_SnackisContext _snackisContext;

        private readonly UserManager<Forum_SnackisUser> _userManager;
        private readonly SignInManager<Forum_SnackisUser> _signInManager;

        [BindProperty(SupportsGet = true)]
        public string Subject { get; set; }
        public List<Thread> Threads { get; set; }
        public List<Insert> Inserts { get; set; }
        public List<Insert> Inserts2 { get; set; }
        public DateTime Latest { get; set; }
        public List<Forum_SnackisUser> Users { get; set; }
        public Forum_SnackisUser MyUser { get; set; }

        public ForumsModel(Forum_SnackisContext snackisContext, UserManager<Forum_SnackisUser> userManager, SignInManager<Forum_SnackisUser> signInManager)
        {
            _snackisContext = snackisContext;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task OnGetAsync()
        {
            Threads = _snackisContext.Threads.ToList();
            Inserts = _snackisContext.Inserts.OrderByDescending(o => o.Date).Take(1).ToList();
            Users = _snackisContext.Users.ToList();
            Inserts2 = _snackisContext.Inserts.ToList();
            MyUser = await _userManager.GetUserAsync(User);
        }

        public int CountInserts(string thread)
        {
            int x = Inserts2.Count(c => c.Thread == thread);
            return x;
        }

        public DateTime LatestInsert(string thread)
        {
            DateTime date = Inserts2.Where(w => w.Thread == thread).Select(s => s.Date).Last();
            return date;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Forum_Snackis.Data;
using Forum_Snackis.Models;
using Microsoft.EntityFrameworkCore;

namespace Forum_Snackis.Pages
{
    public class IndexModel : PageModel
    {
        private readonly Forum_SnackisContext _snackisContext;
        public List<AdminFunctions> AdminFunctions { get; set; }
        public List<Thread> Threads { get; set; }
        public List<Insert> Inserts { get; set; }

      //  private readonly IInsertGateway _gateway;
     //   public List<Insert> GatewayInserts { get; set; }

        public IndexModel(Forum_SnackisContext snackisContext)
        {
            _snackisContext = snackisContext;
         //   _gateway = gateway;
        }

        public async Task OnGetAsync()
        {
            AdminFunctions = await _snackisContext.AdminFunctions.ToListAsync();
            Threads = await _snackisContext.Threads.ToListAsync();
            Inserts = await _snackisContext.Inserts.ToListAsync();
        //    GatewayInserts = await _gateway.GetInserts();
        }

        public int CountThreads(string subject)
        {
            int x = Threads.Where(w => w.Subject == subject).Select(s => s.Name).Count();
            return x;   
        }
        public int CountInserts(string subject)
        {
            int x = Inserts.Where(w => w.Subject == subject).Count();
            return x;
        }

    }
}

Pages/InfoSite.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Forum_Snackis.Areas.Identity.Data;
using Forum_Snackis.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Forum_Snackis.Pages
{
    public class InfoSiteModel : PageModel
    {
        private readonly Forum_SnackisContext _snackisContext;
        private readonly UserManager<Forum_SnackisUser> _userManager;
     

        public Forum_SnackisUser MyUser { get; set; }
        public List<Forum_SnackisUser> Users { get; set; }
        [BindProperty(SupportsGet = true)]
        public string UserNickname { get; set; }

        public InfoSiteModel(UserManager<Forum_SnackisUser> userManager, Forum_SnackisContext snackisContext)
        {
            _userManager = userManager;
            _snackisContext = snackisContext;

        }

        public async Task OnGetAsync()
        {
            MyUser = await _userManager.GetUserAsync(User);
            Users = _snackisContext.Users.ToList();
        }
    }
}

Pages/Insert.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Forum_Snackis.Data;
using Forum_Snackis.Models;
using Forum_Snackis.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;

namespace Forum_Snackis.Pages
{
    public class InsertModel : PageModel
    {
        private readonly Forum_SnackisContext _snackisContext;
        private readonly UserManager<Forum_SnackisUser> _userManager;

        [BindProperty(SupportsGet = true)]
        public string Subject { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Thread { get; set; }
        [BindProperty(SupportsGet = true)]
        public int InsertId { get; set; }
        [BindProperty]
        public string Text { get; set; }
        public List<Insert> Inserts { get; set; }
        [BindProperty]
        public string Writer { get; set; }
        [BindProperty]
        public string WriterNickName { get; set; }
        public Forum_SnackisUser MyUser { get; set; }

        public InsertModel(Forum_SnackisContext snackisContext, UserManager<Forum_SnackisUser> userManager)
        {
            _snackisContext = snackisContext;
            _userManager = userManager;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            MyUser = await _userManager.GetUserAsync(User);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            Insert insert = new Insert();
            insert.Date = DateTime.Now;
            insert.Subject = Subject;
            insert.Thread = Thread;
            insert.Text = Text;
            insert.Writer = Writer;
            insert.WriterNickName = WriterNickName;
            _snackisContext.Inserts.Add(insert);
           await _snackisContext.SaveChangesAsync();

            return RedirectToPage("/Threads", new {Subject = insert.Subject, Thread = insert.Thread });
        }

        public async Task<IActionResult> OnPostSubThread()
        {
            Insert insert = new Insert();
            insert.Date = DateTime.Now;
            insert.Subject = Subject;
            insert.Thread = Thread;
            insert.ParentId = InsertId;
            insert.Text = Text;
            insert.Writer = Writer;
            insert.WriterNickName = WriterNickName;
            

            _snackisContext.Inserts.Add(insert);
            await _snackisContext.SaveChangesAsync();

            return RedirectToPage("/Subthread", new { Subject = insert.Subject, Thread = insert.Thread, InsertId = insert.ParentId });
        }
    }
}

Pages/NewThread.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Forum_Snackis.Data;
using Forum_Snackis.Models;
using Microsoft.AspNetCore.Identity;
using Forum_Snackis.Areas.Identity.Data;

namespace Forum_Snackis.Pages
{
    public class NewThreadModel : PageModel
    {
        private readonly Forum_SnackisContext _snackisContext;
        private readonly UserManager<Forum_SnackisUser> _userManager;
        private readonly SignInManager<Forum_SnackisUser> _signInManager;

        [BindProperty(SupportsGet = true)]
        public string Subject { get; set; }

        [BindProperty]
        public string Name { get; set; }
        public List<Thread> Threads { get; set; }
        public Forum_SnackisUser MyUser { get; set; }
        [BindProperty]
        public string WriterId { get; set; }

        public NewThreadModel(Forum_SnackisContext snackisContext, UserManager<Forum_SnackisUser> userManager, SignInManager<Forum_SnackisUser> signInManager)
        {
            _snackisContext = snackisContext;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task OnGetAsync()
        {
            MyUser = await _userManager.GetUserAsync(User);

        }

        public async  Task<IActionResult> OnPostAsync()
        {
            Thread thread = new Thread();
            thread.Subject = Subject;
            thread.Name = Name;
            thread.WriterId = WriterId;
            _snackisContext.Threads.Add(thread);
            await _snackisContext.SaveChangesAsync();

            return RedirectToPage("/Forums", new { Subject = thread.Subject });
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum_Snackis.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/SubThread.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Forum_Snackis.Pages
{
    public class SubThreadModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Forums.cshtml
@page

@model Forum_Snackis.Pages.ForumsModel
@{
}

<div class="container">
    <h5>@Model.Subject</h5>
    <br />
    @if (Model.MyUser != null)
        {
            <a href="/NewThread?Subject=@Model.Subject"><button type="button" class="btn-primary">Ny tråd</button></a>
        }
        else
        {
            <a href="/NewThread"><button type="button" class="btn-primary">Ny tråd</button></a>
        }
   
    <br />
    <br />

    <div class="row">

        @foreach (var item in Model.Threads)
        {
            @foreach (var user in Model.Users)
            {


                if (item.Subject == Model.Subject && item.WriterId == user.Id)
                {
                <div class="card">
                    <div class="card-body" style="width:1000px">
                        <div class="row">
                            <img src="@user.Photo" class="rounded-circle" style="margin-right: 10px; margin-left: 10px; height: 50px; width: 50px" alt="...">
                            <div style="padding-left: 10px">
                                <a href="./Threads?Subject=@item.Subject&Thread=@item.Name">@item.Name</a>
                                <br />
                                @Model.CountInserts(item.Name) svar    @*- 120 läst*@
                            </div>
                                @*@if (item.Name != null)
                                {
                                <div style="padding-left:700px">
                                    @Model.LatestInsert(item.Name).ToShortDateString() >
                                </div>
                                 }*@
                        </div>
                    </div>
                </div>
                    }
                }
            }
  
    </div>
</div>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Snackis Forum</h1>
</div>
<br />
@{ var groupByHeader = Model.AdminFunctions.GroupBy(g => g.ForumHeader);}
@foreach (var group in groupByHeader)
{
    <div class="container">
        <div class="row">
            <div class="card">
                <div class="card-body" style="width:1000px; background-color:lightgrey">
                    <h6>@group.Key</h6>
                </div>
            </div>
            @foreach (var item in group)
            {
                if (item.Subject != null)
                {

                    <div class="card">
                        <div class="card-body" style="width:1000px">
                            <a href="./Forums?Subject=@item.Subject">@item.Subject</a>
                            <br />

                            @if (item.Description != null)
                            {
                                <div>
                                    @item.Description
                                </div>
                            }

                            @if (Model.CountThreads(item.Subject) != 0 && Model.CountThreads(item.Subject) != 1)
                            {
                                <div>@Model.CountThreads(item.Subject) ämnen - @Model.CountInserts(item.Subject) svar</div>
                            }
                            @if (Model.CountThreads(item.Subject) == 1)
                            {
                            <div>@Model.CountThreads(item.Subject) ämne - @Model.CountInserts(item.Subject) svar</div>
                            }



                        </div>
                        </div>
                        }
                                }
                            </div>
    </div>
    <br />
}

Pages/InfoSite.cshtml
@page
@model Forum_Snackis.Pages.InfoSiteModel
@{
}


<div class="container">
    <div class="card">
<div class="card-body">
    @foreach (var user in Model.Users)
    {
@if (Model.UserNickname == user.NickName)
{
    <div class="text-center">
        <h4>@user.NickName</h4>
        <h5>@user.Hometown</h5>
        <img src="@user.Photo" height="400"  />
        <br />
        <br />
        <p><b>@user.Description</b></p>
    </div>
    }
 }
</div>
    </div>
</div>

Pages/Insert.cshtml
@page
@model Forum_Snackis.Pages.InsertModel
@{
}

@if (Model.MyUser != null && Model.InsertId == 0)
{
    <form method="post">
        <textarea rows="4" cols="70" name="text" placeholder="Skriv här"></textarea>
        <input name="writer" value="@Model.MyUser.Id" hidden />
        <input name="WriterNickName" value="@Model.MyUser.NickName" hidden />
        <br />
        <button type="submit">Spara</button>
    </form>
}
@if (Model.MyUser == null)
{
    <p>Du måste logga in först.</p>
}

@*subthread*@

@if (Model.MyUser != null && Model.InsertId != 0)
{
<form asp-page-handler="subthread" method="post">
    <textarea rows="4" cols="70" name="text" placeholder="Skriv här"></textarea>
    <input name="writer" value="@Model.MyUser.Id" hidden />
    <input name="WriterNickName" value="@Model.MyUser.NickName" hidden />
    <input name="Subject" value="@Model.Subject" hidden />
    <input name="Thread" value="@Model.Thread" hidden />
    <input name="InsertId" value="@Model.InsertId" hidden />
    <br />
    <button type="submit">Spara</button>
</form>
}

Pages/NewThread.cshtml
@page
@model Forum_Snackis.Pages.NewThreadModel
@{
}

@if (Model.MyUser != null)
{
<form method="post">
    <input type="text" name="name" placeholder="Ny tråd" />
    <input name="writerid" value="@Model.MyUser.Id" hidden />
    <button type="submit">Spara</button>
</form>
}
else
{
<p>Du måste logga in först.</p>
}

Pages/SubThread.cshtml
@page
@model Forum_Snackis.Pages.ThreadsModel
@{
}

<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
</head>

<div class="container">



    <h5>@Model.Thread</h5>
    <br />
    @if (Model.MyUser != null)
    {
        <a href="/Insert?Subject=@Model.Subject&Thread=@Model.Thread&InsertId=@Model.InsertId"><button type="button" class="btn-primary">Svara</button></a>
    }
    else
    {
        <a href="/Insert"><button type="button" class="btn-primary">Svara</button></a>
    }

    <br />
    <br />

    <div class="row">

        @foreach (var item in Model.Inserts)
        {
            @foreach (var user in Model.Users)
            {

                if (item.Subject == Model.Subject && item.Thread == Model.Thread && item.Writer == user.Id && item.Id == Model.InsertId)
                {
                    <div class="card" style="margin-bottom:20px">
                        <div class="card-body" style="width:1000px">
                            <div class="row">
                                <div class="col-2">
                                    <img src="@user.Photo" class="rounded-circle" style="margin-right: 10px; margin-left: 10px; height: 50px; width: 50px" alt="...">
                                    <br />
                                    <a href="/InfoSite?UserNickname=@user.NickName">@user.NickName</a>
                                </div>
                                <div class="col-9">
                                    @item.Date
                                    <hr />
                                    @Model.BadFilter(item.Text)
                                    <br />
                                    @if (item.PhotoLink != null)
                                    {
                                        <img src="@item.PhotoLink" class="col-5" />
                                    }
                                    <br />
                                    <ul>
                                        @if (item.Like != 0)
                                        {
                                            <li>Antal likes: @item.Like</li>
                                        }
                                        @if (item.Hearts != 0)
                                        {
                                            <li>Antal hjärtor: @item.Hearts</li>
                                        }
                                        @if (item.Dislike != 0)
                                        {
                                            <li>Antal dissar: @item.Dislike</li>
                                        }
                                    </ul>

                                </div>
                            </div>


                            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                @if (Model.MyUser != null)
                                {
                                    @*<a href="./SubThread?Subject=@item.Subject&Thread=@item.Thread&Id=@item.Id"><button class="btn btn-outline-primary" style="height:45px; margin-right: 10px">Kommentera</button></a>*@
                                    <form asp-page-handler="addlike" method="post">
                                        <button class="btn btn-outline-primary"><span class="material-icons md-18">thumb_up_off_alt</span></button>
                                        <input type="hidden" name="id" value="@item.Id" />
                                    </form>
                                    <form asp-page-handler="addhearts" method="post">
                                        <button class="btn btn-outline-primary"><span class="material-icons md-18">favorite_border</span></button>
                                        <input type="hidden" name="id" value="@item.Id" />
                                    </form>
                                    <form asp-page-handler="adddislike" method="post">
                                        <button class="btn btn-outline-primary" style="margin-right: 10px"><span class="material-icons md-18">sentiment_very_dissatisfied</span></button>
                                        <input type="hidden" name="id" value="@item.Id" />
                                    </form>

                                    <form method="post">
                                        <input name="offensiveid" hidden value="@item.Id" />
                                        <button class="btn btn-outline-primary" type="submit" style="height:45px">Anmäl</button>
                                    </form>
                                }

                            </div>


                            @if (Model.MyUser != null && Model.MyUser.Id == item.Writer)
                            {
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end" id="show">
                                    <form method="post">
                                        <input type="text" name="photolink" placeholder="lägg till bildlänk" />
                                        <input name="insertid" value="@item.Id" hidden />
                                        <br />
                                        <button class="btn btn-outline-primary" type="submit">Spara</button>
                                    </form>
                                </div>
                            }
                            @*<p id="show2"></p>*@
                        </div>
                    </div>
                }
            }
        }

        @foreach (var item in Model.Inserts)
        {
            @foreach (var user in Model.Users)
            {

                if (item.Subject == Model.Subject && item.Thread == Model.Thread && item.Writer == user.Id && item.ParentId == Model.InsertId)
                {
                    <div class="card" style="margin-bottom:20px">
                        <div class="card-body" style="width:1000px">
                            <div class="row">
                                <div class="col-2">
                                    <img src="@user.Photo" class="rounded-circle" style="margin-right: 10px; margin-left: 10px; height: 50px; width: 50px" alt="...">
                                    <br />
                                    <a href="/InfoSite?UserNickname=@user.NickName">@user.NickName</a>
                                </div>
                                <div class="col-9">
                                    @item.Date
                                    <hr />
                                    @Model.BadFilter(item.Text)
                                    <br />
                                    @if (item.PhotoLink != null)
                                    {
                                        <img src="@item.PhotoLink" class="col-5" />
                                    }
                                    <br />
                                    <ul>
                                        @if (item.Like != 0)
                                        {
                                            <li>Antal likes: @item.Like</li>
                                        }
                                        @if (item.Hearts != 0)
                                        {
                                            <li>Antal hjärtor: @item.Hearts</li>
                                        }
                                        @if (item.Dislike != 0)
                                        {
                                            <li>Antal dissar: @item.Dislike</li>
                                        }
                                    </ul>

                                </div>
                            </div>


                            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                @if (Model.MyUser != null)
                                {
                                    <a href="./SubThread?Subject=@item.Subject&Thread=@item.Thread&InsertId=@item.Id"><button class="btn btn-outline-primary" style="height:45px; margin-right: 10px">Kommentera</button></a>
                                    <form asp-page-handler="addlike" method="post">
                                        <button class="btn btn-outline-primary"><span class="material-icons md-18">thumb_up_off_alt</span></button>
                                        <input type="hidden" name="id" value="@item.Id" />
                                    </form>
                                    <form asp-page-handler="addhearts" method="post">
                                        <button class="btn btn-outline-primary"><span class="material-icons md-18">favorite_border</span></button>
                                        <input type="hidden" name="id" value="@item.Id" />
                                    </form>
                                    <form asp-page-handler="adddislike" method="post">
                                        <button class="btn btn-outline-primary" style="margin-right: 10px"><span class="material-icons md-18">sentiment_very_dissatisfied</span></button>
                                        <input type="hidden" name="id" value="@item.Id" />
                                    </form>

                                    <form method="post">
                                        <input name="offensiveid" hidden value="@item.Id" />
                                        <button class="btn btn-outline-primary" type="submit" style="height:45px">Anmäl</button>
                                    </form>
                                }

                            </div>


                            @if (Model.MyUser != null && Model.MyUser.Id == item.Writer)
                            {
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end" id="show">
                                    <form method="post">
                                        <input type="text" name="photolink" placeholder="lägg till bildlänk" />
                                        <input name="insertid" value="@item.Id" hidden />
                                        <br />
                                        <button class="btn btn-outline-primary" type="submit">Spara</button>
                                    </form>
                                </div>
                            }
                            @*<p id="show2"></p>*@
                        </div>
                    </div>
                }
            }
        }
    </div>
</div>

<script>



    function showLink() {

        document.getElementById("show").style = "";
    }
    function showLink2() {

        document.getElementById("show2").innerHTML = "Du måste logga in först"
    }
</script>